version: "3.4"
services:
  db:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_PASSWORD=super-secret
      - POSTGRES_DB=asset_register_api
    ports:
      - "15432:5432"
  web:
    build: 
      context: .
      target: development
    environment:
      - DATABASE_URL=postgres://postgres:super-secret@db:5432/asset_register_api
      - ASPNETCORE_URLS=http://*:5000
      - GOV_NOTIFY_URL=${GOV_NOTIFY_URL}
      - GOV_NOTIFY_API_KEY=${GOV_NOTIFY_API_KEY}
      - EMAIL_WHITELIST=${EMAIL_WHITELIST}
      - HmacSecret="super duper mega secret"
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - '.:/app'
      # persist the home, as cache goes in it
      - 'nuget:/.nuget'
      - 'dotnet:/.dotnet'

volumes:
  nuget:
  dotnet:
